services:
  fail2ban:
    image: linuxserver/fail2ban
    container_name: fail2ban
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - VERBOSITY=-vv
    volumes:
      - /data/docker_data/web/nginx/log:/remotelogs/nginx:ro
      - /var/log:/var/log:ro
      - ./config:/config
