services:
  bililive:
    image: chigusa/bililive-go:latest
    container_name: bililive
    ports:
      - "8039:8080"
    volumes:
      - ./config.yml:/etc/bililive-go/config.yml
      - ./Videos:/srv/bililive
    restart: unless-stopped
