services:
  moments:
    image: kingwrcy/moments:latest
    container_name: moments
    ports:
      - "default_port_1:3000"
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: unless-stopped
