services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    ports:
      - "8989:80"
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=NEXTCLOUD_ADMIN_PASSWORD
    restart: unless-stopped