services:
  webtop:
    image: lscr.io/linuxserver/webtop:ubuntu-kde
    container_name: webtop-ubuntu
    ports:
      - default_port_1:3000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - SUBFOLDER=/
      - TITLE=Webtop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/config
    security_opt:
      - seccomp=unconfined
    shm_size: "1gb"
    restart: unless-stopped
