services:
  zentao-server:
    image: idoop/zentao:latest
    container_name: zentao-server
    ports:
      - "default_port_1:80"
      - "default_port_2:3306"
    environment:
      - ADMINER_USER=root
      - ADMINER_PASSWD=123456
      - BIND_ADDRESS=false
    volumes:
      - ./zentao-server/:/opt/zbox/
    extra_hosts:
      - "smtp.exmail.qq.com:163.177.90.125"
    restart: unless-stopped
